# Generated by Django 3.0.5 on 2020-04-23 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cases', models.IntegerField(default=0)),
                ('death', models.IntegerField(default=0)),
                ('Recover', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 4, 23, 20, 7, 20, 903584, tzinfo=utc))),
            ],
        ),
    ]
