# Generated by Django 3.0.5 on 2020-04-24 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='Active_Cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='New_Deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='New_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='Serious',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='cases_million',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='deaths_million',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='test_million',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 13, 35, 42, 382141, tzinfo=utc)),
        ),
    ]
