# Generated by Django 3.0.5 on 2020-04-24 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_auto_20200424_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 14, 2, 53, 578741, tzinfo=utc)),
        ),
    ]
