# Generated by Django 3.0.5 on 2020-04-26 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0008_auto_20200426_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 12, 16, 49, 169020, tzinfo=utc)),
        ),
    ]
