# Generated by Django 3.0.5 on 2020-04-26 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0011_auto_20200426_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 18, 2, 7, 263855, tzinfo=utc)),
        ),
    ]
