# Generated by Django 3.0.5 on 2020-04-26 22:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0012_auto_20200426_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 22, 10, 53, 608099, tzinfo=utc)),
        ),
    ]
