# Generated by Django 3.0.5 on 2020-04-27 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0014_auto_20200426_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 12, 40, 18, 541996, tzinfo=utc)),
        ),
    ]
