# Generated by Django 3.0.5 on 2020-04-27 15:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0027_auto_20200427_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 15, 12, 51, 188372, tzinfo=utc)),
        ),
    ]
