# Generated by Django 3.0.5 on 2020-04-29 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0032_auto_20200427_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 29, 11, 53, 31, 1619, tzinfo=utc)),
        ),
    ]
