# Generated by Django 3.0.5 on 2020-04-30 18:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0036_auto_20200430_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 18, 0, 55, 571600, tzinfo=utc)),
        ),
    ]
