# Generated by Django 3.0.5 on 2020-07-17 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0041_auto_20200717_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 16, 11, 25, 952195, tzinfo=utc)),
        ),
    ]
