# Generated by Django 3.0.5 on 2020-07-19 09:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0042_auto_20200717_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='Active_Cases',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='New_Deaths',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='New_cases',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='Recover',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='Serious',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='cases',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 9, 27, 2, 825902, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='country',
            name='death',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='tests',
            field=models.FloatField(default=0),
        ),
    ]
