# Generated by Django 3.0.5 on 2020-04-27 15:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StMaroc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2020, 4, 27, 15, 25, 23, 202500, tzinfo=utc))),
                ('cases', models.IntegerField(default='0')),
                ('recov', models.IntegerField(default='0')),
                ('death', models.IntegerField(default='0')),
                ('tests', models.IntegerField(default='0')),
            ],
        ),
    ]
