# Generated by Django 3.0.5 on 2020-04-30 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('StMaroc', '0004_auto_20200429_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stmaroc',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 30, 17, 39, 44, 676443, tzinfo=utc)),
        ),
    ]
