# Generated by Django 3.0.5 on 2020-04-30 18:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('StMaroc', '0007_auto_20200430_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stmaroc',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 30, 18, 0, 55, 573295, tzinfo=utc)),
        ),
    ]
