# Generated by Django 3.0.5 on 2020-07-17 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('StMaroc', '0010_auto_20200717_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stmaroc',
            name='cases',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='stmaroc',
            name='casesD',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='stmaroc',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 17, 13, 2, 26, 611443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stmaroc',
            name='death',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='stmaroc',
            name='deathD',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='stmaroc',
            name='recov',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='stmaroc',
            name='recovD',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='stmaroc',
            name='tests',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='stmaroc',
            name='testsD',
            field=models.FloatField(default='0'),
        ),
    ]
