# Generated by Django 3.0.5 on 2020-07-17 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('StMaroc', '0011_auto_20200717_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stmaroc',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 17, 13, 8, 23, 142385, tzinfo=utc)),
        ),
    ]
