# Generated by Django 3.0.5 on 2020-07-19 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('StMaroc', '0015_auto_20200719_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stmaroc',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 19, 9, 31, 10, 655441, tzinfo=utc)),
        ),
    ]
