# Generated by Django 3.0.5 on 2020-07-20 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('StMaroc', '0018_auto_20200720_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stmaroc',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 20, 14, 16, 40, 473292, tzinfo=utc)),
        ),
    ]
