# Generated by Django 3.0.5 on 2020-04-27 13:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='THe Writter', max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('img', models.ImageField(default='static/default.png', upload_to='static')),
                ('date', models.DateField(default=datetime.datetime(2020, 4, 27, 13, 2, 26, 446547, tzinfo=utc))),
                ('acitve', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
