# Generated by Django 3.0.5 on 2020-04-30 17:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200430_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 30, 17, 48, 44, 739038, tzinfo=utc)),
        ),
    ]
