# Generated by Django 3.0.5 on 2020-07-19 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200719_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 19, 9, 31, 10, 653488, tzinfo=utc)),
        ),
    ]
