# Generated by Django 3.0.5 on 2020-04-30 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2020, 4, 30, 17, 43, 10, 748483, tzinfo=utc))),
                ('casconfirmed', models.CharField(max_length=100)),
                ('casretablis', models.CharField(max_length=100)),
                ('casmorts', models.CharField(max_length=100)),
                ('casexclus', models.CharField(max_length=100)),
            ],
        ),
    ]
