# Generated by Django 3.0.5 on 2020-07-19 09:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_auto_20200719_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fronthome',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 19, 9, 27, 49, 266796, tzinfo=utc)),
        ),
    ]
