# Generated by Django 3.0.5 on 2020-07-20 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_auto_20200719_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fronthome',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 20, 13, 42, 49, 219746, tzinfo=utc)),
        ),
    ]
