# Generated by Django 3.0.5 on 2020-07-20 14:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0014_auto_20200720_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fronthome',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 20, 14, 17, 11, 285366, tzinfo=utc)),
        ),
    ]
