# Generated by Django 3.0.5 on 2020-07-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predict',
            old_name='casesP',
            new_name='fatality_rate',
        ),
        migrations.RenameField(
            model_name='predict',
            old_name='deathP',
            new_name='incubation',
        ),
        migrations.RenameField(
            model_name='predict',
            old_name='recoveredP',
            new_name='mild_recoveryMax',
        ),
        migrations.AddField(
            model_name='predict',
            name='mild_recoveryMin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predict',
            name='percent_mild',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predict',
            name='percent_severe',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predict',
            name='r0',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predict',
            name='serial_interval',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predict',
            name='severe_deathMax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predict',
            name='severe_deathMin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predict',
            name='severe_recoveryMax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='predict',
            name='severe_recoveryMin',
            field=models.FloatField(default=0),
        ),
    ]
